name: swift_care
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  logger: ^1.0.0
  catcher: ^0.6.9
  dio:
  get_storage: ^2.0.3
  cached_network_image: ^3.1.0
  introduction_screen: ^2.1.0
  flutter_easyloading: ^3.0.3
  file_picker: ^4.0.3
  flutter_html: ^2.1.2
  flutter_screenutil: 5.0.1
  pinput: ^1.2.2
  flutter_rating_bar: ^4.0.0
  country_code_picker: ^2.0.2
  device_info_plus:
  image_picker: ^0.8.4+5
  sqflite: ^2.0.2
  fluttertoast:
  google_maps_flutter: ^2.1.1
  syncfusion_flutter_datepicker: ^19.4.52
  image_cropper: ^1.3.1
  flutter_spinkit: ^5.1.0
  translator: ^0.1.7
  flutter_local_notifications: ^9.4.0
  firebase_messaging: ^14.1.3
  firebase_core:
  flutter_paytabs_bridge: 2.2.7
  timeago: ^3.2.2
  plugin_platform_interface: ^2.1.1
  geolocator: 8.2.0
  google_maps_widget: ^1.0.1
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  google_api_headers: ^1.2.0
  place_picker: ^0.9.20-nullsafety
  photo_view: ^0.13.0
  package_info_plus: 1.4.2
  google_fonts: ^3.0.1
  flutter_svg: any
  circle_nav_bar: ^1.0.2
  carousel_slider: ^4.0.0
  carousel_indicator: ^1.0.5
  shaky_animated_listview: ^0.0.5
  readmore: ^2.1.0
  flutter_animated_dialog: ^2.0.1
  auto_size_text: ^3.0.0
  country_picker: ^2.0.18
  material_floating_search_bar: ^0.3.7








dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/




